version: "3.9"
services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: geoplaces-postgres
    environment:
      POSTGRES_USER: geoplaces
      POSTGRES_PASSWORD: geoplaces
      POSTGRES_DB: geoplacesdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
